plugins/nextcloud-rule-exclusions-before.conf

TX variables in phase 1 are overwritten by the CRS initialization. Moving them to phase 2 does *not* fix the issue but is in line with the how the rules were executed before they were moved into the plugin.
Relates to #2

fix: Adjust phases for rules setting TX variables

---

plugins/nextcloud-rule-exclusions-before.conf

In [this commit](https://github.com/coreruleset/coreruleset/commit/5a47465f9cee33d46ac62b03fd300195bbee8c2f) made three years ago, the 'phase' values for some rules were reduced, including the rule [911100](https://github.com/coreruleset/coreruleset/commit/5a47465f9cee33d46ac62b03fd300195bbee8c2f#diff-74c2e602499bf7b7a23dbbe1bbb2ba1251c466e60ab3c3684210bb2aef042773) which is responsible for handling request methods. The NextCloud DAV functionality doesn't work with the previous values.

decrease the 'phase' values

---

CONTRIBUTORS.md
plugins/nextcloud-rule-exclusions-before.conf

As discussed on Slack, this is needed for proper modification of `tx.allowed_request_content_type` by exclusion rules. Plugins are currently running before CRS initialization so variables like `tx.allowed_request_content_type` needs to be initialized also by plugins if they are going to be modified.

feat: Copy of tx.allowed_request_content_type initialization

---

CONTRIBUTORS.md
plugins/nextcloud-rule-exclusions-before.conf

As promised in my last PR, here are 10 more FPs. There are a few more FPs, but I forgot to label them as PL 1 and they got mixed with my PL 2 FPs. @theseion if you find a typo or mistake, kindly make changes where necessary. Thank you.
Also, we need to update the plugin version to **1.0.1**, as done with WordPress plugin.

Fix for few FPs

---

plugins/nextcloud-rule-exclusions-before.conf

This PR fixes a few false positives
1. Rules for fixing false positives when logging in, changing passwords, logging out etc assume the Nextcloud instance is not using [pretty URLs](https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#pretty-urls). I've removed  ``/index.php`` which should work for Nextcloud instances that both are and aren't using [pretty URLs](https://docs.nextcloud.com/server/latest/admin_manual/installation/source_installation.html#pretty-urls).
2. Fix few additional false positives with Nextcloud Text app including when accessing Nextcloud Text app via a public share.
3. Fix false positives with adding custom CSS code via Nextcloud Custom CSS app.
I've done ``ctl:ruleRemoveTargetByTag=OWASP_CRS;ARGS"`` for 9508128 and 9508129 …

Fix FP when logging in, Nextcloud Text app and when adding custom CSS code

---

plugins/nextcloud-rule-exclusions-before.conf

**Versions**
- Nextcloud 27.0.0.8
- Nginx 1.24.0 build with ModSecurity 3.0.8
- OWASP_CRS/4.0.0-nightly (updated)
**Issue**
Accessing file details in the file manager throws FPs for the following URLs:
/remote.php/dav/systemtags-relations/files/
/remote.php/dav/systemtags/
/remote.php/dav/versions/_USERNAME_/versions/
**Reason**
TX:content_type' (Value: `|text/plain|`
is not allowed.
I can provide detailed logs if needed.
Thanks for your consideration.

Address FP in NC 27 file manager - details - versioning and system tags

---

plugins/nextcloud-rule-exclusions-before.conf

This PR fixes the following
1. Marks capturing group regex as non capturing
2. Tighten rule exclusion rules to be more precise
3. Fix FP when disabling dyslexia font
4. Fix FP when viewing the trashbin
5. Fix FP with Sharing files/folders
6. Remove duplicate rules

Remove Duplicate rules, fix FPs and Tighten a few rules

---

plugins/nextcloud-rule-exclusions-before.conf

Allow text/plain and switch on XML parser for /remote.php/dav/photos/\<username\>/albums|sharedalbums|places.
Please review the username regex ([allowed characters](https://docs.nextcloud.com/server/latest/admin_manual/configuration_user/user_configuration.html#creating-a-new-user)). I'm not sure if the urlencoded '@' character is necessary.

fix FP for photos app (albums, sharedalbums, places)

---

plugins/nextcloud-rule-exclusions-before.conf

- Ignore PHP injections on file names during uploads
- Remove duplicate rule
Fixes #38

fix: don't inspect REQUEST_FILENAME of uploads

---

plugins/nextcloud-rule-exclusions-before.conf

this fixes a regression when restoring a file to an older version by only using the xml parser for text/plain content type

fix: xml parser failure when restoring file to old version

---

plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508978.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508991.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508992.yaml

Some recent changes to Nextcloud Mail in the past few months have introduced a few additional false positives, this PR resolves those new false positives.

fix: sending mail and adjusting settings FP with newer NC mail versions

---

plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508993.yaml

I created this PR to handle false positive when using the deck application in nextcloud
When moving a card,the PUT method is not allowed.
Content of arg "description" triggers multiple rules.

Fix: False positive in deck application

---

plugins/nextcloud-rule-exclusions-before.conf

SecAction rules can't be disabled via a ctl action or run time rule exclusion
This can be problematic in reverse proxy deployments where you only want to enable the Nextcloud plugin for your Nextcloud domain.
This PR fixes that by replacing the SecAction with a SecRule that's functionally the exact same, except now it can be disabled via a ctl action.

fix: SecAction can't be disabled via ctl action

---

plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508122.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508311.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508312.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508313.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508314.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508315.yaml

This PR mostly fixes issues with session tokens that are only an issue at PL-2 and above, but there is a fix for using the markdown test editor in public shares. 
The tests for some of these rules were very large(This PR would've been above 700 lines, but now it's about 300), so I refactored them by using a ``|`` to test against multiple URIs with the same payload, but for whatever reason the nginx regression tests are failing while the apache tests are passing.

fix: text editor in public share and token related FPs

---

plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508311.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508312.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508313.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508314.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508315.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508400.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508401.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508402.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508411.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508420.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508624.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508628.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508633.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508852.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508880.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508978.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508991.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508992.yaml

With the CRS v4 images, it has become apparent that plugin tests were being run at paranoia level 1. Now, they are running at paranoia level 4, revealing some mistakes in the tests and rules.

fix: rules and tests after running at paranoia level 4

---

CONTRIBUTORS.md
plugins/nextcloud-rule-exclusions-before.conf

Adds a rule similar to 9508602 & 9508603 to prevent blocking discovering WebDAV on /.well-known:
```
ModSecurity: Warning. Matched "Operator `Within' with parameter `GET HEAD POST OPTIONS PUT' against variable `REQUEST_METHOD' (Value: `PROPFIND' ) [file "/usr/local/nginx/conf/conf.d/include/coreruleset/rules/REQUEST-911-METHOD-ENFORCEMENT.conf"] [line "28"] [id "911100"] [rev ""] [msg "Method is not allowed by policy"] [data "PROPFIND"] [severity "2"] [ver "OWASP_CRS/4.0.0"] [maturity "0"] [accuracy "0"] [tag "application-multi"] [tag "language-multi"] [tag "platform-multi"] [tag "attack-generic"] [tag "paranoia-level/1"] [tag "OWASP_CRS"] [tag "capec/1000/210/272/220/274"] [tag "PCI/12.1"] [hostname "172.19.0.7"] [uri "/.well-known/webdav/xxx/"] [unique_id "171119327475.703982"] [ref …
```

fix: .well-known/webdav fp

---

plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508510.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508511.yaml

Fixes false positives when requesting a static file at pl-2 or higher with the ver argument. I haven't done any character whitelisting since this is just used for static files, there's nothing to attack.

fix: requesting a static file at pl-2

---

plugins/nextcloud-rule-exclusions-before.conf

A previous pull request removed XPath XML, this has caused a regression with XML content and introduced some new false positives. This PR reverts those changes

fix: fp regression with xml content

---

README.md

Documents which apps in Nextcloud are supported. This should prevent confusion on false positives with apps that aren't supported.

docs: list supported/unsupported apps

---

plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508600.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508604.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508605.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508609.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508611.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508612.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508613.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508614.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508616.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508618.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508640.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508643.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508644.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508645.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508651.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508652.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508653.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508654.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508655.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508670.yaml

Over the past year the Nextcloud plugin has grown dramatically in size with improved coverage and support for various features within Nextcloud, this has come at the expense of code readability and maintainability. Rule IDs have grown from 53 to 185 and the lines of code from 780 to 2756.
This PR is focused on overhauling personal/administration settings and has:
- Reduced the number of rules down to 181 (from 185)
- Rule exclusions have been reorganized to make it easier to find/modify/add rule exclusions relating to settings
- Comment clarity has been improved
- 6 Additional tests have been added
The Nextcloud plugin will likely remain large since Nextcloud incredibly feature rich, but it's a start.

refactor: overhaul and cleanup rule exclusions for settings

---

plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508171.yaml

Nextcloud has recently renamed the endpoint for entering passwords in public shares from ``/s/random/authenticate/showShare`` to ``/s/random/authenticate/showshare`` causing the rule that handles false positives with passwords to no longer match. This PR makes that rule case insensitive.

fix: use case insensitivity for public shares when entering passwords

---

README.md
plugins/nextcloud-rule-exclusions-before.conf

Updates the docs on how to increase the max file upload size for file uploads. Newer versions of Nextcloud upload files to the remote.php endpoint

docs: update locations for increasing max file upload size

---

plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508952.yaml

Fix false positive when creating/viewing a photo album by making the `/` at the end optional.

fix: creating/viewing an album in photos app

---

README.md
plugins/nextcloud-rule-exclusions-before.conf
plugins/nextcloud-rule-exclusions-config.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508118.yaml
tests/regression/nextcloud-rule-exclusions-plugin/9508119.yaml

This PR adds a workaround for the Nextcloud iOS app not setting the correct content type when uploading files making it impossible for CRS to parse it (Pretty much every single CRS rule is triggered). Since I've essentially disabled all rules for the request body (Excluding the `REQUEST_BODY` variable) I fear that this might cause something similar to [CVE-2021-35368](https://nvd.nist.gov/vuln/detail/CVE-2021-35368) so I've disabled the workaround by default but given an option to enable the workaround for those that need it. I've done what I could to minimize the risk/impact of a bypass for those that need this functionality, but I'm not fully satisfied with the solution.

fix: add workaround for ios file upload issue

---

plugins/nextcloud-rule-exclusions-before.conf

Adds a workaround for https://github.com/owasp-modsecurity/ModSecurity/issues/3356 when setting `SecRequestBodyNoFilesLimit` to a high value for libModSecurity3 users. This workaround has only been tested against the configuration recommendations in the plugin readme.

fix: add workaround for libmodsecurity3 bug

---

plugins/nextcloud-rule-exclusions-before.conf

This PR removes rule exclusions for Nextcloud versions older than 24 and some EOL apps. 
Drops app support for:
Ransomware protection (No new release since 2022, does not support any actively maintained version of Nextcloud)
Ownnote (No commits since 2019)
Bookmarks (Support will be added back in a future PR with tests)

chore: remove old rule exclusions

---

README.md

By default Coraza activates the `URLENCODED` body parser when no other parser has been configured, this behavior can cause issues when uploading files in Nextcloud.
resolves: #122

docs: document issue with coraza default body parser

---

README.md
plugins/nextcloud-rule-exclusions-before.conf
tests/regression/nextcloud-rule-exclusions-plugin/9508240.yaml

Adds support for the external app which allows the integration of non-nextcloud apps either via an iframe, a redirect, or a link in the login page.

feat: add support for integrating external apps
