- .github/workflows/integration.yaml
- .github/workflows/lint.yaml
- CONTRIBUTORS.md
- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508115.yaml
Fixes [#3024](https://github.com/coreruleset/coreruleset/issues/3024)
> Fixing FP with PDF upload

- plugins/nextcloud-rule-exclusions-before.conf
* Avatars not loading in Nextcloud Desktop
* Cannot open plain text files in File Manager
> fix: avatars and plain text files FPs

- plugins/nextcloud-rule-exclusions-before.conf
Let me know if you guys need the necessary logs for these FPs.
Also, @theseion can you look into [this issue](https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/issues/16)?
> Fix few FPs

- plugins/nextcloud-rule-exclusions-before.conf
Added two more FPs and rearranged One FP to a similar rule.
> fix webauthn and authtoken FPs

- plugins/nextcloud-rule-exclusions-before.conf
- Updated phase values for allowed content types
- Added one new FP
> fix: update phase values for allowed content types

- plugins/nextcloud-rule-exclusions-before.conf
This pull request fixes the following
1. Minor formatting issues regarding CRS guidelines, I used the CRS rules check tool to find these issues.
2. False positives when changing settings for Photos, Contacts, Notes and Shares.
3. Fixed false positive when creating/deleting/modifying Circles.
> Fix FP with Photos, Circles, Notes, Contacts, Files and Settings

- plugins/nextcloud-rule-exclusions-before.conf
Fixes false positives with the Nextcloud Mail client
> Add support for Nextcloud Mail

- plugins/nextcloud-rule-exclusions-before.conf
> Actions order

- plugins/nextcloud-rule-exclusions-before.conf
Fixes issue https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/issues/34
> Fix XML parser failing

- plugins/nextcloud-rule-exclusions-before.conf
Closes https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/issues/6 
I also fixed a few additional FP I noticed while working on this issue
> Resolve FPs reported under issue 6

- plugins/nextcloud-rule-exclusions-before.conf
This PR fixes the following
1. Adds support for Nextcloud Recognize
2. Fix FP when changing passwords
3. Fix FP when changing sorting direction in Files
4. Fix FP when deleting a mailbox
5. Fix FP with cookies
6. Fix FP with text editor
7. Fix another search FP
8. Removes some duplicate rules (and also fixes another FP)
9. Fix FP when setting up a new Nextcloud Server
> Fix Recognize, Passwords, Cookie, Text Editor, Search, and deleting mailbox FPs

- README.md
- plugins/nextcloud-rule-exclusions-before.conf
- plugins/nextcloud-rule-exclusions-config.conf
This PR fixes most FPs relating to file uploads, there still may be one or two that I missed.
I also noticed some exclusions commented out, should I document them in the readme as well since it's a bit hidden?
https://github.com/EsadCetiner/nextcloud-rule-exclusions-plugin/blob/7e2c4064e050febc06cbdb093fb80867ece88fb2/plugins/nextcloud-rule-exclusions-before.conf#L23
closes https://github.com/coreruleset/nextcloud-rule-exclusions-plugin/issues/5 and https://github.com/coreruleset/coreruleset/issues/2973
> Fix: various file upload FPs

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508176.yaml
> fix: file uploads FP from Windows client

- plugins/nextcloud-rule-exclusions-before.conf
> fix: request smuggling FP when uploading via android client

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508880.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508881.yaml
Adds support for the smart picker used within mail, text app, notes, office and talk.
I haven't tested any of the AI features since I don't have that setup
> feat: add support for smart picker

- README.md
- plugins/nextcloud-rule-exclusions-before.conf
- plugins/nextcloud-rule-exclusions-config.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508628.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508629.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508630.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508631.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508632.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508850.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508852.yaml
Fixes various false positives when adjusting user settings, or administrator settings.
> fix: false positives when adjusting various settings

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508530.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508533.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508540.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508541.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508550.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508551.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508553.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508633.yaml
This PR adds support for the Nextcloud Office connector, built in CODE Server and the dedicated Collabora Server
closes #54
> feat: add support for Nextcloud Office

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508810.yaml
I updated the rule added in #53 to allow to `PUT` method when moving cards, un-assigning users and setting a due date.
> Allow the PUT method globally in the deck app.

- CHANGELOG
- plugins/nextcloud-rule-exclusions-before.conf
- plugins/nextcloud-rule-exclusions-config.conf
@EsadCetiner just added support for Nextcloud Office. This warrants a new release, IMO.
> chore: update version to 1.1.0

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508954.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508955.yaml
> fix: opening an image on public share

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508172.yaml
> fix: fp with creating/uploading shares and files

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508815.yaml
> fix: reordering card stacks in deck fp

- README.md
- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508720.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508721.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508722.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508723.yaml
Adds support for Nextcloud Cookbook. I haven't tested against the mobile apps since I can't find any official apps.
~~I had to use scalar value ``>-`` to avoid ``200002`` from being triggered and to send the payload correctly, but the linter isn't happy with it.~~
closes #88
> feat: add support for Nextcloud Cookbook

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508641.yaml
Fixes a regression introduced in #86 
I've added tests to make sure this doesn't happen again.
> fix: fp regression in carddav

- README.md
- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508640.yaml
- tests/regression/nextcloud-rule-exclusions-plugin/9508840.yaml
Adds support for the Nextcloud News RSS feed aggregator
> feat: add support for nextcloud news

- plugins/nextcloud-rule-exclusions-before.conf
> fix: files recommendations false positive on ios app

- plugins/nextcloud-rule-exclusions-before.conf
- tests/regression/nextcloud-rule-exclusions-plugin/9508320.yaml
> fix: editing contacts via nextcloud web gui
